#!/usr/bin/env python3
import base64
import os
import sys


def slice_string(text: str, char_count: int):
    slice_length = len(text) // char_count
    last_slice = len(text) % char_count

    for index in range(slice_length):
        yield f"{text[char_count * index:char_count + char_count * index:1]}\n"
    else:
        yield f"{text[-last_slice:]}\n"


count_args = len(sys.argv)

if count_args == 2:
    file = sys.argv[1]
    check_file = os.path.exists(file)
    file_name = os.path.splitext(file)[0]

    if check_file:
        with open(file, "rb") as image_file, open(f'{file_name}.txt', 'w') as result_file:
            encoded_string = base64.b64encode(image_file.read()).decode("utf-8")

            for line in slice_string(encoded_string, 76):
                result_file.write(line)
    else:
        print("Source file does not exist")
else:
    print(f"Invalid number of arguments [{count_args - 1}]")
