#!/usr/bin/env python3
import subprocess

NAME_OF_THE_GAME = ''
GAME_PATH = ''
MANGOHUD_OPENGL = False

if __name__ == '__main__':
    args = ['zenity', '--question', f'--title={NAME_OF_THE_GAME}',
            '--text=Запустить вместе с mangohud?', '--width=250', '--height=80']
    process = subprocess.Popen(args, text=True)

    process.communicate()
    if not process.returncode:
        if MANGOHUD_OPENGL:
            subprocess.call(['mangohud', '--dlsym', 'wine', GAME_PATH])
        else:
            subprocess.call(['mangohud', 'wine', GAME_PATH])
    else:
        subprocess.call(['wine', GAME_PATH])